# Kash Base Image
# Builds the single kash binary (used for both CLI and server).
# Published as a multi-arch image (amd64 + arm64) to ghcr.io/akashicode/kash.
# Agent Dockerfiles (generated by `kash init`) use this as their base image.

FROM golang:1.25-alpine AS builder

WORKDIR /build

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Version stamping, passed by the release workflow. Without these the published
# image reports "kash dev": the builder image has no git, so the binary carries
# no VCS stamp to fall back on either.
ARG VERSION=dev
ARG COMMIT=none
ARG BUILD_DATE=unknown

# Build the binary (CGO disabled for static linking)
RUN CGO_ENABLED=0 go build -trimpath \
    -ldflags="-s -w -X github.com/akashicode/kash/cmd.version=${VERSION} -X github.com/akashicode/kash/cmd.commit=${COMMIT} -X github.com/akashicode/kash/cmd.buildDate=${BUILD_DATE}" \
    -o /kash ./cmd/kash

# --- Minimal runtime stage ---
FROM alpine:3.19

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

COPY --from=builder /kash /app/kash

ENTRYPOINT ["/app/kash"]
