# Agent-Forge Base Image
# Builds the single agentforge binary (used for both CLI and server).
# Published as a multi-arch image (amd64 + arm64) to ghcr.io/agent-forge/agentforge.
# Agent Dockerfiles (generated by `agentforge init`) use this as their base image.

FROM golang:1.22-alpine AS builder

WORKDIR /build

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the binary (CGO disabled for static linking)
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" \
    -o /agentforge ./cmd/agent-forge

# --- Minimal runtime stage ---
FROM alpine:3.19

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

COPY --from=builder /agentforge /app/agentforge

ENTRYPOINT ["/app/agentforge"]
